groups:
  - name: link-generation
    jobs: 
      - run-generation-integration
  - name: link-ingestion
    jobs:
      - run-ingestion-integration

jobs:
  - name: run-generation-integration
    serial_groups: 
      - link-generation
    on_failure: *destroy-generation-instance
    plan:
      - task: create-generation-instance
        config:
          params:
            DESIRED_CAPACITY: 1
            ASG_NAME: related-links-generation
            ROLE_ARN: ((concourse_role_arn))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run: &update-asg
            path: bash
            args:
              - -c
              - |
                set -e pipefail
                eval $(aws-assume-role $ROLE_ARN)
                echo Assumed role successfully
                aws autoscaling set-desired-capacity \
                  --auto-scaling-group-name $ASG_NAME \
                  --desired-capacity $DESIRED_CAPACITY \
                  --region eu-west-1
                echo Set desired-capacity
      - task: wait-for-instance
        config:
          params:
            ROLE_ARN: ((concourse_role_arn))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run:
            path: bash
            args:
              - -c
              - |
                set -ueo pipefail

                eval $(aws-assume-role $ROLE_ARN)
                echo Assumed role successfully

                echo "Sleeping for 30s to give AWS chance to start EC2..."
                sleep 30

                instance_id=$(aws ec2 describe-instances --region eu-west-1 --query "Reservations[*].Instances[*].InstanceId" --filters Name=instance-state-name,Values=running,pending  Name=tag:Name,Values=related-links-generation --output=text)
                
                echo "Waiting on instance ${instance_id}..."

                aws ec2 wait instance-status-ok \
                  --region eu-west-1 \
                  --instance-ids ${instance_id}
                
                echo "Instance available and ready"
      - task: provision-instance
        config:
          params:
            CONCOURSE_PRIVATE_KEY: ((concourse_private_key))
            BIG_QUERY_CREDENTIALS: ((big_query_credentials))
            ROLE_ARN: ((concourse_role_arn))
            CONTENT_STORE_BUCKET: ((content_store_bucket_integration))
            RELATED_LINKS_BUCKET: ((related_links_bucket_integration))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run:
            path: bash
            args:
              - -c
              - |
                set -eo pipefail

                eval $(aws-assume-role $ROLE_ARN)
                echo Assumed role successfully

                echo "$CONCOURSE_PRIVATE_KEY" > /tmp/concourse_ssh_key
                chmod 400 /tmp/concourse_ssh_key

                instance_ip=$(aws ec2 describe-instances --region eu-west-1 --query "Reservations[*].Instances[*].PublicIpAddress" --filter Name=tag:Name,Values=related-links-generation --output=text)
                
                echo "Connecting to instance..."
                ssh -i /tmp/concourse_ssh_key -o StrictHostKeyChecking=no ubuntu@${instance_ip} << EOF
                  echo "Connected!"

                  # Setup data directory
                  sudo mkdir /var/data
                  sudo chown ubuntu /var/data

                  # Setup Github directory
                  mkdir /var/data/github
                  cd /var/data/github

                  # Clone related links repository
                  git clone https://github.com/alphagov/govuk-related-links-recommender.git
                  cd govuk-related-links-recommender

                  # Set execute permission on scripts
                  chmod +x ./provision_generation_machine
                  chmod +x ./run_link_generation

                  # Make bucket names accessible to scripts
                  export CONTENT_STORE_BUCKET="$CONTENT_STORE_BUCKET"
                  export RELATED_LINKS_BUCKET="$RELATED_LINKS_BUCKET"
                  export BIG_QUERY_CREDENTIALS='$BIG_QUERY_CREDENTIALS'

                  # Create log file
                  touch /var/tmp/related_links_process.log

                  echo "Provisioning machine..."
                  ./provision_generation_machine

                  echo "Running link generation in background..."
                  echo "Writing log to /var/tmp/related_links_process.log"
                  ./run_link_generation > /var/tmp/related_links_process.log 2>&1 &
                EOF
      - task: watch-instance
        config:
          params:
            CONCOURSE_PRIVATE_KEY: ((concourse_private_key))
            ROLE_ARN: ((concourse_role_arn))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run:
            path: bash
            args:
              - -c
              - |
                set -eo pipefail

                eval $(aws-assume-role $ROLE_ARN)
                echo Assumed role successfully

                echo "$CONCOURSE_PRIVATE_KEY" > /tmp/concourse_ssh_key
                chmod 400 /tmp/concourse_ssh_key

                # Update SSH config to keep connection alive
                echo "ServerAliveInterval 300" >> /etc/ssh/ssh_config

                instance_id=$(aws ec2 describe-instances --region eu-west-1 --query "Reservations[*].Instances[*].PublicIpAddress" --filter Name=tag:Name,Values=related-links-generation --output=text)
                
                echo "Connecting to instance..."
                ssh -i /tmp/concourse_ssh_key -o StrictHostKeyChecking=no ubuntu@${instance_id} <<EOF
                  echo "Connected!"

                  cd /var/data/github/govuk-related-links-recommender

                  chmod +x ./monitor_related_links_process

                  ./monitor_related_links_process
                EOF
      - &destroy-generation-instance
        task: destroy-generation-instance
        config:
          params:
            DESIRED_CAPACITY: 0
            ASG_NAME: related-links-generation
            ROLE_ARN: ((concourse_role_arn))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run: *update-asg

  - name: run-ingestion-integration
    serial_groups: 
      - link-ingestion
    on_failure: *destroy-ingestion-instance
    plan:
      - task: create-ingestion-instance
        config:
          params:
            DESIRED_CAPACITY: 1
            ASG_NAME: related-links-ingestion
            ROLE_ARN: ((concourse_role_arn))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run: *update-asg
      - task: wait-for-instance
        config:
          params:
            ROLE_ARN: ((concourse_role_arn))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run:
            path: bash
            args:
              - -c
              - |
                set -ueo pipefail

                eval $(aws-assume-role $ROLE_ARN)
                echo Assumed role successfully

                echo "Sleeping for 30s to give AWS chance to start EC2..."
                sleep 30

                instance_id=$(aws ec2 describe-instances --region eu-west-1 --query "Reservations[*].Instances[*].InstanceId" --filters Name=instance-state-name,Values=running,pending  Name=tag:Name,Values=related-links-ingestion --output=text)
                
                echo "Waiting on instance ${instance_id}..."

                aws ec2 wait instance-status-ok \
                  --region eu-west-1 \
                  --instance-ids ${instance_id}
                
                echo "Instance available and ready"
      - task: provision-ingestion-instance
        config:
          params:
            CONCOURSE_PRIVATE_KEY: ((concourse_private_key))
            ROLE_ARN: ((concourse_role_arn))
            PUBLISHING_API_URI: ((publishing_api_uri_integration))
            PUBLISHING_API_BEARER_TOKEN: ((publishing_api_bearer_token_integration))
            RELATED_LINKS_BUCKET: ((related_links_bucket_integration))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run:
            path: bash
            args:
              - -c
              - |
                set -ueo pipefail

                eval $(aws-assume-role $ROLE_ARN)
                echo Assumed role successfully

                echo "$CONCOURSE_PRIVATE_KEY" > /tmp/concourse_ssh_key
                chmod 400 /tmp/concourse_ssh_key

                instance_ip=$(aws ec2 describe-instances --region eu-west-1 --query "Reservations[*].Instances[*].PublicIpAddress" --filter Name=tag:Name,Values=related-links-ingestion --output=text)
                
                echo "Connecting to instance ${instance_ip}..."
                ssh -i /tmp/concourse_ssh_key -o StrictHostKeyChecking=no ubuntu@${instance_ip} << EOF
                  echo "Connected!"

                  # Setup data directory
                  sudo mkdir /var/data
                  sudo chown ubuntu /var/data

                  # Setup Github directory
                  mkdir /var/data/github
                  cd /var/data/github

                  # Clone related links repository
                  git clone https://github.com/alphagov/govuk-related-links-recommender.git
                  cd govuk-related-links-recommender

                  # Set execute permission on scripts
                  chmod +x ./provision_ingestion_machine
                  chmod +x ./run_link_ingestion

                  # Make environment variables accessible to scripts
                  export RELATED_LINKS_BUCKET="$RELATED_LINKS_BUCKET"
                  export PUBLISHING_API_URI="$PUBLISHING_API_URI"
                  export PUBLISHING_API_BEARER_TOKEN="$PUBLISHING_API_BEARER_TOKEN"

                  # Create log file
                  touch /var/tmp/related_links_process.log

                  echo "Provisioning machine..."
                  ./provision_ingestion_machine

                  echo "Running link ingestion in background..."
                  echo "Writing log to /var/tmp/related_links_process.log"
                  ./run_link_ingestion > /var/tmp/related_links_process.log 2>&1 &
                EOF
      - task: watch-ingestion-instance
        config:
          params:
            CONCOURSE_PRIVATE_KEY: ((concourse_private_key))
            ROLE_ARN: ((concourse_role_arn))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run:
            path: bash
            args:
              - -c
              - |
                set -ueo pipefail

                eval $(aws-assume-role $ROLE_ARN)
                echo Assumed role successfully

                echo "$CONCOURSE_PRIVATE_KEY" > /tmp/concourse_ssh_key
                chmod 400 /tmp/concourse_ssh_key

                # Update SSH config to keep connection alive
                echo "ServerAliveInterval 300" >> /etc/ssh/ssh_config

                instance_ip=$(aws ec2 describe-instances --region eu-west-1 --query "Reservations[*].Instances[*].PublicIpAddress" --filter Name=tag:Name,Values=related-links-ingestion --output=text)
                
                echo "Connecting to instance..."
                ssh -i /tmp/concourse_ssh_key -o StrictHostKeyChecking=no ubuntu@${instance_ip} <<EOF
                  echo "Connected!"

                  cd /var/data/github/govuk-related-links-recommender

                  chmod +x ./monitor_related_links_process

                  ./monitor_related_links_process
                EOF
      - &destroy-ingestion-instance
        task: destroy-ingestion-instance
        config:
          params:
            DESIRED_CAPACITY: 0
            ASG_NAME: related-links-ingestion
            ROLE_ARN: ((concourse_role_arn))
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: govsvc/task-toolbox
              tag: 1.1.0
          run: *update-asg

