FROM ubuntu:18.04

# Prepare container to compile python via pyenv
RUN apt-get update -y
RUN apt-get upgrade -y

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --yes python3 python3-distutils python3-pip curl git gcc make zlib1g zlib1g-dev libreadline-dev libbz2-dev libssl-dev build-essential libreadline-dev libsqlite3-dev wget llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10



# Install pyenv
RUN curl https://pyenv.run | bash

# Setup project
WORKDIR /root
COPY . .

RUN export PYENV_ROOT="$HOME/.pyenv" \
  && export PATH="$PYENV_ROOT/bin:$PATH" \
  && eval "$(pyenv init -)" \
  && pyenv install -s 3.6.9 \
  && pyenv local 3.6.9 \
  && pip3 install -r requirements.txt

ARG PYENV_ROOT="$HOME/.pyenv"
ARG PATH="$PYENV_ROOT/bin:$PATH"
ARG DATA_DIR=./data
ARG MODEL_DIR=./models
ARG GOOGLE_APPLICATION_CREDENTIALS="tmp/bigquery.json"


CMD python -m src.run_all
