#!/bin/bash

set -eo pipefail

LINK_PROCESS_PID="$(ps aux | grep run_link_ | grep -v grep | awk '{print $2}')"
echo "PID of the link generation / ingestion process is $LINK_PROCESS_PID"

tail -f --pid=$LINK_PROCESS_PID /var/tmp/related_links_process.log

exit_code=0
LOG_LAST_LINE=$(tail -n 1 /var/tmp/related_links_process.log)
if [ "$LOG_LAST_LINE" != "related_links process succeeded" ]; then
    echo "Unexpected last line. It looks like the process failed."
    exit_code=1
else
    echo "Process finished successfully."
fi

exit $exit_code
