#!/bin/bash

set -eo pipefail

LINK_PROCESS_PID="$(ps aux | grep run_link_ | grep -v grep | awk '{print $2}')"
echo "PID of the link generation / ingestion process is $LINK_PROCESS_PID"

# Run a continuous loop in the background, checking memory usage every 5 minutes
while /bin/true; do
    echo "== mem check =="
    date
    free -h
    echo "==============="
    sleep 300
done &

MEM_CHECK_PID=$!

tail -f --pid=$LINK_PROCESS_PID /var/tmp/related_links_process.log /var/log/syslog

# Stop the memory check loop
kill -9 $MEM_CHECK_PID


LOG_LAST_LINE=$(tail -n 1 /var/tmp/related_links_process.log)
if [ "$LOG_LAST_LINE" != "related_links process succeeded" ]; then
    echo "Unexpected last line. It looks like the process failed."
    exit 1
else
    echo "Process finished successfully."
fi
