#!/bin/bash

set -eo pipefail

# Install RVM dependencies
sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq curl g++ gcc autoconf automake bison libc6-dev libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev make pkg-config sqlite3 zlib1g-dev libgmp-dev libreadline-dev libssl-dev

# Install RVM and Ruby 2.6.3
curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
curl -sSL https://get.rvm.io | bash -s stable

source ~/.rvm/scripts/rvm
rvm install 2.7.3

# Set execute permission on scripts
chmod +x ./run_link_ingestion
chmod +x ./monitor_related_links_process

sudo touch /var/tmp/related_links_process.log
sudo chown -R ubuntu:ubuntu /var/tmp/related_links_process.log

echo "Done provisioning machine"
