#!/bin/bash

set -eo pipefail

# Install Mongo
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
sudo apt-get update -y
sudo apt-get install -y mongodb-org
sudo service mongod start

# Install Python 3 and Pip
sudo apt-get install -y python3.6
sudo apt install -y python3-pip

# Set execute permission on scripts
chmod +x ./run_link_generation
chmod +x ./monitor_related_links_process

sudo touch /var/tmp/related_links_process.log
sudo chown -R ubuntu:ubuntu /var/tmp/related_links_process.log

echo "Done provisioning machine"
