#!/bin/bash

set -ueo pipefail

export DATA_DIR=$PWD/data
export MODEL_DIR=$PWD/models
export GOOGLE_APPLICATION_CREDENTIALS=/var/tmp/bigquery.json

# Temporary
# sudo apt-get update -y
# sudo apt-get install -y awscli
# sudo apt-get install -y jq

# Store Big Query credentials
echo $BIG_QUERY_CREDENTIALS > /var/tmp/bigquery.json
chmod 400 /var/tmp/bigquery.json

echo "Finding latest content backup..."
# Find and download the latest content store backup from S3
LATEST_CONTENT_BACKUP_PATH=$(aws s3api list-objects-v2 --bucket $CONTENT_STORE_BUCKET --query "Contents[?contains(Key, '-content_store_production.gz')]" | jq  -c "max_by(.LastModified)|.Key" | xargs)

echo "Downloading latest content store backup..."
echo "${LATEST_CONTENT_BACKUP_PATH}"
aws s3 cp s3://$CONTENT_STORE_BUCKET/$LATEST_CONTENT_BACKUP_PATH /var/data/latest_content_store_backup.gz

# Extract content store backup
cd /var/data
tar -xvf latest_content_store_backup.gz
ls -lat content_store_production

# Restore content store data to MongoDb
mongorestore -d content_store -c content_items /var/data/content_store_production/content_items.bson

# Install requirements
cd /var/data/github/govuk-related-links-recommender
pip3 install -r requirements.txt

# Create the structural network
# python3 src/data_preprocessing/get_content_store_data.py

# Create the functional network
# python3 src/data_preprocessing/make_functional_edges_and_weights.py

# Create the network
# python3 src/features/make_network.py

# Train the model
# python3 src/models/train_node2vec_model.py

# Predict related links!
# python3 src/models/predict_related_links.py

# Run orchestration scipt
python3 src/run_all.py

cd /var/data/github/govuk-related-links-recommender/data/predictions

SUGGESTED_LINKS_CSV="$(ls -t | grep suggested_related_links.csv | head -1)"
SUGGESTED_LINKS_JSON="$(ls -t | grep suggested_related_links.json | head -1)"

# Copy outputs to S3
aws s3 cp $DATA_DIR/predictions/$SUGGESTED_LINKS_JSON s3://$RELATED_LINKS_BUCKET/related_links.json
aws s3 cp $DATA_DIR/predictions/$SUGGESTED_LINKS_CSV s3://$RELATED_LINKS_BUCKET/related_links.csv

aws s3 cp $DATA_DIR/tmp/structural_edges.csv s3://$RELATED_LINKS_BUCKET/structural_edges.csv
aws s3 cp $DATA_DIR/tmp/functional_edges.csv s3://$RELATED_LINKS_BUCKET/functional_edges.csv
aws s3 cp $DATA_DIR/tmp/network.csv s3://$RELATED_LINKS_BUCKET/network.csv
aws s3 cp $MODEL_DIR/n2v.model s3://$RELATED_LINKS_BUCKET/n2v.model





