name: CI
on: [push]
jobs:
  Run-Python-Tests-and-Linting:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build tests container
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: related-links-tests:latest
      -
        name: Run tests
        uses: addnab/docker-run-action@v3
        with:
            image: related-links-tests:latest
            run: flake8 src && pytest tests/unit
            options: -v ${{ github.workspace }}:/opt

  Run-Ruby-Tests:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        shell: bash
        run: |
          set -eo pipefail
          gem install bundler
          bundle install
          rspec spec
